s=set()
n=input("enter num:")
s.add(int(n))
n=input("enter num:")
s.add(int(n))
n=input("enter num:")
s.add(int(n))
n=input("enter num:")
s.add(int(n))
n=input("enter num:")
s.add(int(n))
n=input("enter num:")
s.add(int(n))
n=input("enter num:")
s.add(int(n))
n=input("enter num:")
s.add(int(n))

print(s)